services:
  backend:
    build: .
    ports:
      - "5001:5000"
    command: sh -c "/wait && /server"

    environment:
      - POSTGRES_HOST=postgres
      - WAIT_HOSTS=postgres:5432
    volumes:
      - ./configs/.env:/configs/.env
  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: