services:
  backend:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
    command: sh -c "/wait && /server"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - WAIT_HOSTS=postgres:5432, redis:6379
    volumes:
      - ./configs/.env:/configs/.env

  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: "redis:6-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    volumes:
      - redis-data:/data
volumes:
  pg-data:
  redis-data: