definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
  controller.DefaultHttpError:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  title: JWT Auth Demo Project
paths:
  /auth/login:
    post:
      parameters:
      - description: Login information
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.DefaultHttpError'
      summary: Logins a user
      tags:
      - Auth
  /auth/register:
    post:
      parameters:
      - description: Registration information
        in: body
        name: registerData
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.DefaultHttpError'
      summary: Registers a new user
      tags:
      - Auth
swagger: "2.0"
