definitions:
  auth.DefaultHttpError:
    properties:
      message:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
info:
  contact: {}
  title: JWT Auth Demo Project
paths:
  /auth/register:
    post:
      parameters:
      - description: Registration information
        in: body
        name: registerData
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.DefaultHttpError'
      summary: Register a new user
swagger: "2.0"
