definitions:
  handler.DefaultHttpError:
    properties:
      message:
        type: string
    type: object
  handler.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handler.LoginResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  handler.LogoutRequest:
    properties:
      refreshToken:
        type: string
    type: object
  handler.RefreshRequest:
    properties:
      refreshToken:
        type: string
    type: object
  handler.RefreshResponse:
    properties:
      accessToken:
        type: string
    type: object
  handler.RegisterRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
info:
  contact: {}
  title: JWT Auth Demo Project
paths:
  /auth/login:
    post:
      parameters:
      - description: Login information
        in: body
        name: loginData
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
      summary: Logins a user
      tags:
      - Auth
  /auth/logout:
    post:
      parameters:
      - description: Refresh token
        in: body
        name: logoutData
        required: true
        schema:
          $ref: '#/definitions/handler.LogoutRequest'
      responses:
        "200":
          description: Logged out
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
      summary: Logouts a user
      tags:
      - Auth
  /auth/refresh:
    post:
      parameters:
      - description: Refresh token
        in: body
        name: refreshData
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RefreshResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
      summary: Refreshes access token
      tags:
      - Auth
  /auth/register:
    post:
      parameters:
      - description: Registration information
        in: body
        name: registerData
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.DefaultHttpError'
      summary: Registers a new user
      tags:
      - Auth
swagger: "2.0"
